### ISSUE TITLE
link to documentation in README is broken

### ISSUE THREAD

**Issue by andreas-h** [spectraphilic/reflexible#10]
at https://reflexible.readthedocs.io/, there's only a 404 error (or rather, readthedoc's version of it)

**Comment by FrancescAlted** [comment]
Fixed in https://github.com/spectraphilic/reflexible/commit/0f856a6770191ef2af5ae5045895e3d0e48485a7 and some tweaks suggested in: http://read-the-docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
