### ISSUE TITLE
Test failure: Attempted relative import beyond toplevel package

### ISSUE THREAD

**Issue by andreas-h** [spectraphilic/reflexible#27]
On my machine, running the tests as advised in the README fails:

    $ PYTHONPATH=. python -c "import reflexible; reflexible.test()"
    -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    reflexible version: 0.5.0
    NumPy version:     1.13.3
    Python version:    2.7.14 |Anaconda, Inc.| (default, Mar 12 2018, 12:37:12) 
    [GCC 7.2.0]
    Platform:          linux2-x86_64
    Byte-ordering:     little
    -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    E
    ======================================================================
    ERROR: tests.test_mapdb (unittest.loader.ModuleImportFailure)
    ----------------------------------------------------------------------
    ImportError: Failed to import test module: tests.test_mapdb
    Traceback (most recent call last):
      File "/home/stud_tpl/miniconda3/envs/flexpart/lib/python2.7/unittest/loader.py", line 254, in _find_tests
        module = self._get_module_from_name(name)
      File "/home/stud_tpl/miniconda3/envs/flexpart/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
        __import__(name)
      File "/home/stud_tpl/flexpart/reflexible/reflexible/tests/test_mapdb.py", line 3, in <module>
        from ..mapping import map_regions
    ValueError: Attempted relative import beyond toplevel package
    
    
    ----------------------------------------------------------------------
    Ran 1 test in 0.000s
    
    FAILED (errors=1)

**Comment by jfburkhart** [comment]
There was a poor import statement. This is fixed now. I note however, you are using python 2.7 which we don't really support.

**Comment by andreas-h** [comment]
Thanks for the super-quick reply, I really appreciate it!

Is there a mention of "Python 3 only" anywhere in the 
documentation?  I couldn't find any ...

**Comment by jfburkhart** [comment]
Maybe not, but I should fix that. I think 2.7 still works, but I don't intend to support it...
